headers = []

[functions]

[functions.emails]
included_files = ["./emails/**"]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

[plugins.inputs]

[build]
publish = "C:\\Users\\M JUNAID AHSAN\\Desktop\\devlyx\\new_site2\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]